---
name: Feature Request
about: Suggest an idea for Snapvc
title: "[Feature] "
labels: enhancement
assignees: ''

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature to improve Snapvc!
  - type: textarea
    id: description
    attributes:
      label: Describe the feature
      description: A clear and concise description of what you'd like to happen.
      placeholder: I want to be able to...
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Why is this feature important?
      description: Describe the value or impact of this feature.
      placeholder: This would help me...
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives you've considered
      description: Have you considered any alternative solutions or workarounds?
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context, references, or screenshots about the feature request here.
